//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/crypto/engines/AESEngine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgSpongycastleCryptoEnginesAESEngine")
#ifdef RESTRICT_OrgSpongycastleCryptoEnginesAESEngine
#define INCLUDE_ALL_OrgSpongycastleCryptoEnginesAESEngine 0
#else
#define INCLUDE_ALL_OrgSpongycastleCryptoEnginesAESEngine 1
#endif
#undef RESTRICT_OrgSpongycastleCryptoEnginesAESEngine

#if !defined (OrgSpongycastleCryptoEnginesAESEngine_) && (INCLUDE_ALL_OrgSpongycastleCryptoEnginesAESEngine || defined(INCLUDE_OrgSpongycastleCryptoEnginesAESEngine))
#define OrgSpongycastleCryptoEnginesAESEngine_

#define RESTRICT_OrgSpongycastleCryptoBlockCipher 1
#define INCLUDE_OrgSpongycastleCryptoBlockCipher 1
#include "org/spongycastle/crypto/BlockCipher.h"

@class IOSByteArray;
@protocol OrgSpongycastleCryptoCipherParameters;

/*!
 @brief an implementation of the AES (Rijndael), from FIPS-197.
 <p>
  For further details see: <a href="http://csrc.nist.gov/encryption/aes/">http://csrc.nist.gov/encryption/aes/</a>.
  This implementation is based on optimizations from Dr. Brian Gladman's paper and C code at 
 <a href="http://fp.gladman.plus.com/cryptography_technology/rijndael/">http://fp.gladman.plus.com/cryptography_technology/rijndael/</a>
  There are three levels of tradeoff of speed vs memory
  Because java has no preprocessor, they are written as three separate classes from which to choose
  The fastest uses 8Kbytes of static tables to precompute round calculations, 4 256 word tables for encryption
  and 4 for decryption.
  The middle performance version uses only one 256 word table for each, for a total of 2Kbytes,
  adding 12 rotate operations per round to compute the values contained in the other tables from
  the contents of the first.
  The slowest version uses no static tables at all and computes the values in each round. 
 <p>
  This file contains the middle performance version with 2Kbytes of static tables for round precomputation.
 */
@interface OrgSpongycastleCryptoEnginesAESEngine : NSObject < OrgSpongycastleCryptoBlockCipher >

#pragma mark Public

/*!
 @brief default constructor - 128 bit block size.
 */
- (instancetype)init;

- (NSString *)getAlgorithmName;

- (jint)getBlockSize;

/*!
 @brief initialise an AES cipher.
 @param forEncryption whether or not we are for encryption.
 @param params the parameters required to set up the cipher.
 @throw IllegalArgumentExceptionif the params argument is
  inappropriate.
 */
- (void)init__WithBoolean:(jboolean)forEncryption
withOrgSpongycastleCryptoCipherParameters:(id<OrgSpongycastleCryptoCipherParameters>)params OBJC_METHOD_FAMILY_NONE;

- (jint)processBlockWithByteArray:(IOSByteArray *)inArg
                          withInt:(jint)inOff
                    withByteArray:(IOSByteArray *)outArg
                          withInt:(jint)outOff;

- (void)reset;

@end

J2OBJC_STATIC_INIT(OrgSpongycastleCryptoEnginesAESEngine)

FOUNDATION_EXPORT void OrgSpongycastleCryptoEnginesAESEngine_init(OrgSpongycastleCryptoEnginesAESEngine *self);

FOUNDATION_EXPORT OrgSpongycastleCryptoEnginesAESEngine *new_OrgSpongycastleCryptoEnginesAESEngine_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSpongycastleCryptoEnginesAESEngine *create_OrgSpongycastleCryptoEnginesAESEngine_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleCryptoEnginesAESEngine)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgSpongycastleCryptoEnginesAESEngine")
