//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/bouncycastle/BufferedBlockCipher.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/aowagie/text/pdf/bouncycastle/BufferedBlockCipher.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/System.h"
#include "org/spongycastle/crypto/BlockCipher.h"
#include "org/spongycastle/crypto/CipherParameters.h"
#include "org/spongycastle/crypto/DataLengthException.h"
#include "org/spongycastle/crypto/OutputLengthException.h"
#include "org/spongycastle/crypto/StreamCipher.h"

#if !__has_feature(objc_arc)
#error "com/aowagie/text/pdf/bouncycastle/BufferedBlockCipher must be compiled with ARC (-fobjc-arc)"
#endif

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/bouncycastle/BufferedBlockCipher.java"


#line 18
@implementation ComAowagieTextPdfBouncycastleBufferedBlockCipher

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 32
- (instancetype)init {
  ComAowagieTextPdfBouncycastleBufferedBlockCipher_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 41
- (instancetype)initWithOrgSpongycastleCryptoBlockCipher:(id<OrgSpongycastleCryptoBlockCipher>)cipher {
  ComAowagieTextPdfBouncycastleBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(self, cipher);
  return self;
}


#line 72
- (id<OrgSpongycastleCryptoBlockCipher>)getUnderlyingCipher {
  
#line 74
  return cipher_;
}


#line 86
- (void)init__WithBoolean:(jboolean)forEncryption
withOrgSpongycastleCryptoCipherParameters:(id<OrgSpongycastleCryptoCipherParameters>)params {
  
#line 91
  self->forEncryption_ = forEncryption;
  
#line 93
  [self reset];
  
#line 95
  [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) init__WithBoolean:forEncryption withOrgSpongycastleCryptoCipherParameters:params];
}


#line 103
- (jint)getBlockSize {
  
#line 105
  return [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) getBlockSize];
}


#line 116
- (jint)getUpdateOutputSizeWithInt:(jint)len {
  
#line 119
  jint total = len + bufOff_;
  jint leftOver;
  
#line 122
  if (pgpCFB_) {
    
#line 124
    if (forEncryption_) {
      
#line 126
      leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_))->size_) - ([((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) getBlockSize] + 2);
    }
    else {
      
#line 130
      leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_))->size_);
    }
  }
  else {
    
#line 135
    leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_))->size_);
  }
  
#line 138
  return total - leftOver;
}


#line 149
- (jint)getOutputSizeWithInt:(jint)length {
  
#line 153
  return length + bufOff_;
}


#line 166
- (jint)processByteWithByte:(jbyte)inArg
              withByteArray:(IOSByteArray *)outArg
                    withInt:(jint)outOff {
  
#line 172
  jint resultLen = 0;
  
#line 174
  *IOSByteArray_GetRef(nil_chk(buf_), bufOff_++) = inArg;
  
#line 176
  if (bufOff_ == buf_->size_) {
    
#line 178
    resultLen = [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) processBlockWithByteArray:buf_ withInt:0 withByteArray:outArg withInt:outOff];
    bufOff_ = 0;
  }
  
#line 182
  return resultLen;
}


#line 197
- (jint)processBytesWithByteArray:(IOSByteArray *)inArg
                          withInt:(jint)inOff
                          withInt:(jint)len
                    withByteArray:(IOSByteArray *)outArg
                          withInt:(jint)outOff {
  
#line 205
  if (len < 0) {
    
#line 207
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"Can't have a negative input length!");
  }
  
#line 210
  jint blockSize = [self getBlockSize];
  jint length = [self getUpdateOutputSizeWithInt:len];
  
#line 213
  if (length > 0) {
    
#line 215
    if ((outOff + length) > ((IOSByteArray *) nil_chk(outArg))->size_) {
      
#line 217
      @throw new_OrgSpongycastleCryptoOutputLengthException_initWithNSString_(@"output buffer too short");
    }
  }
  
#line 221
  jint resultLen = 0;
  jint gapLen = ((IOSByteArray *) nil_chk(buf_))->size_ - bufOff_;
  
#line 224
  if (len > gapLen) {
    
#line 226
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(inArg, inOff, buf_, bufOff_, gapLen);
    
#line 228
    resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) processBlockWithByteArray:buf_ withInt:0 withByteArray:outArg withInt:outOff];
    
#line 230
    bufOff_ = 0;
    len -= gapLen;
    inOff += gapLen;
    
#line 234
    while (len > ((IOSByteArray *) nil_chk(buf_))->size_) {
      
#line 236
      resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) processBlockWithByteArray:inArg withInt:inOff withByteArray:outArg withInt:outOff + resultLen];
      
#line 238
      len -= blockSize;
      inOff += blockSize;
    }
  }
  
#line 243
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(inArg, inOff, buf_, bufOff_, len);
  
#line 245
  bufOff_ += len;
  
#line 247
  if (bufOff_ == ((IOSByteArray *) nil_chk(buf_))->size_) {
    
#line 249
    resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) processBlockWithByteArray:buf_ withInt:0 withByteArray:outArg withInt:outOff + resultLen];
    bufOff_ = 0;
  }
  
#line 253
  return resultLen;
}


#line 270
- (jint)doFinalWithByteArray:(IOSByteArray *)outArg
                     withInt:(jint)outOff {
  
#line 275
  @try {
    
#line 277
    jint resultLen = 0;
    
#line 279
    if (outOff + bufOff_ > ((IOSByteArray *) nil_chk(outArg))->size_) {
      
#line 281
      @throw new_OrgSpongycastleCryptoOutputLengthException_initWithNSString_(@"output buffer too short for doFinal()");
    }
    
#line 284
    if (bufOff_ != 0) {
      
#line 286
      if (!partialBlockOkay_) {
        
#line 288
        @throw new_OrgSpongycastleCryptoDataLengthException_initWithNSString_(@"data not block size aligned");
      }
      
#line 291
      [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) processBlockWithByteArray:buf_ withInt:0 withByteArray:buf_ withInt:0];
      resultLen = bufOff_;
      bufOff_ = 0;
      JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(buf_, 0, outArg, outOff, resultLen);
    }
    
#line 297
    return resultLen;
  }
  @finally {
    
#line 301
    [self reset];
  }
}


#line 309
- (void)reset {
  
#line 314
  for (jint i = 0; i < ((IOSByteArray *) nil_chk(buf_))->size_; i++) {
    
#line 316
    *IOSByteArray_GetRef(buf_, i) = 0;
  }
  
#line 319
  bufOff_ = 0;
  
#line 324
  [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_)) reset];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleCryptoBlockCipher;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 6, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 7, 8, 9, -1, -1, -1 },
    { NULL, "I", 0x1, 10, 11, 9, -1, -1, -1 },
    { NULL, "I", 0x1, 12, 13, 14, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithOrgSpongycastleCryptoBlockCipher:);
  methods[2].selector = @selector(getUnderlyingCipher);
  methods[3].selector = @selector(init__WithBoolean:withOrgSpongycastleCryptoCipherParameters:);
  methods[4].selector = @selector(getBlockSize);
  methods[5].selector = @selector(getUpdateOutputSizeWithInt:);
  methods[6].selector = @selector(getOutputSizeWithInt:);
  methods[7].selector = @selector(processByteWithByte:withByteArray:withInt:);
  methods[8].selector = @selector(processBytesWithByteArray:withInt:withInt:withByteArray:withInt:);
  methods[9].selector = @selector(doFinalWithByteArray:withInt:);
  methods[10].selector = @selector(reset);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "buf_", "[B", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "bufOff_", "I", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "forEncryption_", "Z", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "cipher_", "LOrgSpongycastleCryptoBlockCipher;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "partialBlockOkay_", "Z", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "pgpCFB_", "Z", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgSpongycastleCryptoBlockCipher;", "init", "ZLOrgSpongycastleCryptoCipherParameters;", "LJavaLangIllegalArgumentException;", "getUpdateOutputSize", "I", "getOutputSize", "processByte", "B[BI", "LOrgSpongycastleCryptoDataLengthException;LJavaLangIllegalStateException;", "processBytes", "[BII[BI", "doFinal", "[BI", "LOrgSpongycastleCryptoDataLengthException;LJavaLangIllegalStateException;LOrgSpongycastleCryptoInvalidCipherTextException;" };
  static const J2ObjcClassInfo _ComAowagieTextPdfBouncycastleBufferedBlockCipher = { "BufferedBlockCipher", "com.aowagie.text.pdf.bouncycastle", ptrTable, methods, fields, 7, 0x1, 11, 6, -1, -1, -1, -1, -1 };
  return &_ComAowagieTextPdfBouncycastleBufferedBlockCipher;
}

@end


#line 32
void ComAowagieTextPdfBouncycastleBufferedBlockCipher_init(ComAowagieTextPdfBouncycastleBufferedBlockCipher *self) {
  NSObject_init(self);
}


#line 32
ComAowagieTextPdfBouncycastleBufferedBlockCipher *new_ComAowagieTextPdfBouncycastleBufferedBlockCipher_init() {
  J2OBJC_NEW_IMPL(ComAowagieTextPdfBouncycastleBufferedBlockCipher, init)
}


#line 32
ComAowagieTextPdfBouncycastleBufferedBlockCipher *create_ComAowagieTextPdfBouncycastleBufferedBlockCipher_init() {
  J2OBJC_CREATE_IMPL(ComAowagieTextPdfBouncycastleBufferedBlockCipher, init)
}


#line 41
void ComAowagieTextPdfBouncycastleBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(ComAowagieTextPdfBouncycastleBufferedBlockCipher *self, id<OrgSpongycastleCryptoBlockCipher> cipher) {
  NSObject_init(self);
  
#line 44
  self->cipher_ = cipher;
  
#line 46
  self->buf_ = [IOSByteArray newArrayWithLength:[((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher)) getBlockSize]];
  self->bufOff_ = 0;
  
#line 52
  NSString *name = [cipher getAlgorithmName];
  jint idx = [((NSString *) nil_chk(name)) java_indexOf:'/'] + 1;
  
#line 55
  self->pgpCFB_ = (idx > 0 && [name java_hasPrefix:@"PGP" offset:idx]);
  
#line 57
  if (self->pgpCFB_ || [OrgSpongycastleCryptoStreamCipher_class_() isInstance:cipher]) {
    
#line 59
    self->partialBlockOkay_ = true;
  }
  else {
    
#line 63
    self->partialBlockOkay_ = (idx > 0 && ([name java_hasPrefix:@"OpenPGP" offset:idx]));
  }
}


#line 41
ComAowagieTextPdfBouncycastleBufferedBlockCipher *new_ComAowagieTextPdfBouncycastleBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(id<OrgSpongycastleCryptoBlockCipher> cipher) {
  J2OBJC_NEW_IMPL(ComAowagieTextPdfBouncycastleBufferedBlockCipher, initWithOrgSpongycastleCryptoBlockCipher_, cipher)
}


#line 41
ComAowagieTextPdfBouncycastleBufferedBlockCipher *create_ComAowagieTextPdfBouncycastleBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(id<OrgSpongycastleCryptoBlockCipher> cipher) {
  J2OBJC_CREATE_IMPL(ComAowagieTextPdfBouncycastleBufferedBlockCipher, initWithOrgSpongycastleCryptoBlockCipher_, cipher)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAowagieTextPdfBouncycastleBufferedBlockCipher)
