//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/bouncycastle/MultiBlockCipher.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAowagieTextPdfBouncycastleMultiBlockCipher")
#ifdef RESTRICT_ComAowagieTextPdfBouncycastleMultiBlockCipher
#define INCLUDE_ALL_ComAowagieTextPdfBouncycastleMultiBlockCipher 0
#else
#define INCLUDE_ALL_ComAowagieTextPdfBouncycastleMultiBlockCipher 1
#endif
#undef RESTRICT_ComAowagieTextPdfBouncycastleMultiBlockCipher

#if !defined (ComAowagieTextPdfBouncycastleMultiBlockCipher_) && (INCLUDE_ALL_ComAowagieTextPdfBouncycastleMultiBlockCipher || defined(INCLUDE_ComAowagieTextPdfBouncycastleMultiBlockCipher))
#define ComAowagieTextPdfBouncycastleMultiBlockCipher_

#define RESTRICT_OrgSpongycastleCryptoBlockCipher 1
#define INCLUDE_OrgSpongycastleCryptoBlockCipher 1
#include "org/spongycastle/crypto/BlockCipher.h"

@class IOSByteArray;

/*!
 @brief Base interface for a cipher engine capable of processing multiple blocks at a time.
 */
@protocol ComAowagieTextPdfBouncycastleMultiBlockCipher < OrgSpongycastleCryptoBlockCipher, JavaObject >

/*!
 @brief Return the multi-block size for this cipher (in bytes).
 @return the multi-block size for this cipher in bytes.
 */
- (jint)getMultiBlockSize;

/*!
 @brief Process blockCount blocks from input in offset inOff and place the output in
  out from offset outOff.
 @param inArg input data array.
 @param inOff start of input data in in.
 @param blockCount number of blocks to be processed.
 @param outArg output data array.
 @param outOff start position for output data.
 @return number of bytes written to out.
 @throw DataLengthExceptionif offset error occurs.
 @throw IllegalStateExceptionif using invalid data.
 */
- (jint)processBlocksWithByteArray:(IOSByteArray *)inArg
                           withInt:(jint)inOff
                           withInt:(jint)blockCount
                     withByteArray:(IOSByteArray *)outArg
                           withInt:(jint)outOff;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAowagieTextPdfBouncycastleMultiBlockCipher)

J2OBJC_TYPE_LITERAL_HEADER(ComAowagieTextPdfBouncycastleMultiBlockCipher)

#endif

#pragma pop_macro("INCLUDE_ALL_ComAowagieTextPdfBouncycastleMultiBlockCipher")
