//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/bouncycastle/PAdESDefaultBufferedBlockCipher.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/aowagie/text/pdf/bouncycastle/MultiBlockCipher.h"
#include "com/aowagie/text/pdf/bouncycastle/PAdESDefaultBufferedBlockCipher.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/System.h"
#include "org/spongycastle/crypto/BlockCipher.h"
#include "org/spongycastle/crypto/BufferedBlockCipher.h"
#include "org/spongycastle/crypto/CipherParameters.h"
#include "org/spongycastle/crypto/DataLengthException.h"
#include "org/spongycastle/crypto/OutputLengthException.h"
#include "org/spongycastle/crypto/StreamCipher.h"

#if !__has_feature(objc_arc)
#error "com/aowagie/text/pdf/bouncycastle/PAdESDefaultBufferedBlockCipher must be compiled with ARC (-fobjc-arc)"
#endif

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/bouncycastle/PAdESDefaultBufferedBlockCipher.java"


#line 21
@implementation ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 37
- (instancetype)init {
  ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 46
- (instancetype)initWithOrgSpongycastleCryptoBlockCipher:(id<OrgSpongycastleCryptoBlockCipher>)cipher {
  ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(self, cipher);
  return self;
}


#line 87
- (id<OrgSpongycastleCryptoBlockCipher>)getUnderlyingCipher {
  
#line 89
  return cipher_PAdESDefaultBufferedBlockCipher_;
}


#line 101
- (void)init__WithBoolean:(jboolean)forEncryption
withOrgSpongycastleCryptoCipherParameters:(id<OrgSpongycastleCryptoCipherParameters>)params {
  
#line 106
  self->forEncryption_PAdESDefaultBufferedBlockCipher_ = forEncryption;
  
#line 108
  [self reset];
  
#line 110
  [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) init__WithBoolean:forEncryption withOrgSpongycastleCryptoCipherParameters:params];
}


#line 118
- (jint)getBlockSize {
  
#line 120
  return [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) getBlockSize];
}


#line 131
- (jint)getUpdateOutputSizeWithInt:(jint)len {
  
#line 134
  jint total = len + bufOff_PAdESDefaultBufferedBlockCipher_;
  jint leftOver;
  
#line 137
  if (pgpCFB_PAdESDefaultBufferedBlockCipher_) {
    
#line 139
    if (forEncryption_PAdESDefaultBufferedBlockCipher_) {
      
#line 141
      leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_) - ([((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) getBlockSize] + 2);
    }
    else {
      
#line 145
      leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_);
    }
  }
  else {
    
#line 150
    leftOver = JreIntMod(total, ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_);
  }
  
#line 153
  return total - leftOver;
}


#line 164
- (jint)getOutputSizeWithInt:(jint)length {
  
#line 167
  if (pgpCFB_PAdESDefaultBufferedBlockCipher_ && forEncryption_PAdESDefaultBufferedBlockCipher_) {
    
#line 169
    return length + bufOff_PAdESDefaultBufferedBlockCipher_ + ([((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) getBlockSize] + 2);
  }
  
#line 173
  return length + bufOff_PAdESDefaultBufferedBlockCipher_;
}


#line 186
- (jint)processByteWithByte:(jbyte)inArg
              withByteArray:(IOSByteArray *)outArg
                    withInt:(jint)outOff {
  
#line 192
  jint resultLen = 0;
  
#line 194
  *IOSByteArray_GetRef(nil_chk(buf_PAdESDefaultBufferedBlockCipher_), bufOff_PAdESDefaultBufferedBlockCipher_++) = inArg;
  
#line 196
  if (bufOff_PAdESDefaultBufferedBlockCipher_ == buf_PAdESDefaultBufferedBlockCipher_->size_) {
    
#line 198
    resultLen = [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) processBlockWithByteArray:buf_PAdESDefaultBufferedBlockCipher_ withInt:0 withByteArray:outArg withInt:outOff];
    bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
  }
  
#line 202
  return resultLen;
}


#line 217
- (jint)processBytesWithByteArray:(IOSByteArray *)inArg
                          withInt:(jint)inOff
                          withInt:(jint)len
                    withByteArray:(IOSByteArray *)outArg
                          withInt:(jint)outOff {
  
#line 225
  if (len < 0) {
    
#line 227
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"Can't have a negative input length!");
  }
  
#line 230
  jint blockSize = [self getBlockSize];
  jint length = [self getUpdateOutputSizeWithInt:len];
  
#line 233
  if (length > 0) {
    
#line 235
    if ((outOff + length) > ((IOSByteArray *) nil_chk(outArg))->size_) {
      
#line 237
      @throw new_OrgSpongycastleCryptoOutputLengthException_initWithNSString_(@"output buffer too short");
    }
  }
  
#line 241
  jint resultLen = 0;
  jint gapLen = ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_ - bufOff_PAdESDefaultBufferedBlockCipher_;
  
#line 244
  if (len > gapLen) {
    
#line 246
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(inArg, inOff, buf_PAdESDefaultBufferedBlockCipher_, bufOff_PAdESDefaultBufferedBlockCipher_, gapLen);
    
#line 248
    resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) processBlockWithByteArray:buf_PAdESDefaultBufferedBlockCipher_ withInt:0 withByteArray:outArg withInt:outOff];
    
#line 250
    bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
    len -= gapLen;
    inOff += gapLen;
    
#line 254
    if (mbCipher_ != nil) {
      
#line 256
      jint blockCount = JreIntDiv(len, [mbCipher_ getMultiBlockSize]);
      
#line 258
      if (blockCount > 0) {
        
#line 260
        resultLen += [((id<ComAowagieTextPdfBouncycastleMultiBlockCipher>) nil_chk(mbCipher_)) processBlocksWithByteArray:inArg withInt:inOff withInt:blockCount withByteArray:outArg withInt:outOff + resultLen];
        
#line 262
        jint processed = blockCount * [((id<ComAowagieTextPdfBouncycastleMultiBlockCipher>) nil_chk(mbCipher_)) getMultiBlockSize];
        
#line 264
        len -= processed;
        inOff += processed;
      }
    }
    else {
      
#line 270
      while (len > ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_) {
        
#line 272
        resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) processBlockWithByteArray:inArg withInt:inOff withByteArray:outArg withInt:outOff + resultLen];
        
#line 274
        len -= blockSize;
        inOff += blockSize;
      }
    }
  }
  
#line 280
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(inArg, inOff, buf_PAdESDefaultBufferedBlockCipher_, bufOff_PAdESDefaultBufferedBlockCipher_, len);
  
#line 282
  bufOff_PAdESDefaultBufferedBlockCipher_ += len;
  
#line 284
  if (bufOff_PAdESDefaultBufferedBlockCipher_ == ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_) {
    
#line 286
    resultLen += [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) processBlockWithByteArray:buf_PAdESDefaultBufferedBlockCipher_ withInt:0 withByteArray:outArg withInt:outOff + resultLen];
    bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
  }
  
#line 290
  return resultLen;
}


#line 307
- (jint)doFinalWithByteArray:(IOSByteArray *)outArg
                     withInt:(jint)outOff {
  
#line 312
  @try {
    
#line 314
    jint resultLen = 0;
    
#line 316
    if (outOff + bufOff_PAdESDefaultBufferedBlockCipher_ > ((IOSByteArray *) nil_chk(outArg))->size_) {
      
#line 318
      @throw new_OrgSpongycastleCryptoOutputLengthException_initWithNSString_(@"output buffer too short for doFinal()");
    }
    
#line 321
    if (bufOff_PAdESDefaultBufferedBlockCipher_ != 0) {
      
#line 323
      if (!partialBlockOkay_PAdESDefaultBufferedBlockCipher_) {
        
#line 325
        @throw new_OrgSpongycastleCryptoDataLengthException_initWithNSString_(@"data not block size aligned");
      }
      
#line 328
      [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) processBlockWithByteArray:buf_PAdESDefaultBufferedBlockCipher_ withInt:0 withByteArray:buf_PAdESDefaultBufferedBlockCipher_ withInt:0];
      resultLen = bufOff_PAdESDefaultBufferedBlockCipher_;
      bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
      JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(buf_PAdESDefaultBufferedBlockCipher_, 0, outArg, outOff, resultLen);
    }
    
#line 334
    return resultLen;
  }
  @finally {
    
#line 338
    [self reset];
  }
}


#line 346
- (void)reset {
  
#line 351
  for (jint i = 0; i < ((IOSByteArray *) nil_chk(buf_PAdESDefaultBufferedBlockCipher_))->size_; i++) {
    
#line 353
    *IOSByteArray_GetRef(buf_PAdESDefaultBufferedBlockCipher_, i) = 0;
  }
  
#line 356
  bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
  
#line 361
  [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher_PAdESDefaultBufferedBlockCipher_)) reset];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleCryptoBlockCipher;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 6, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 7, 8, 9, -1, -1, -1 },
    { NULL, "I", 0x1, 10, 11, 9, -1, -1, -1 },
    { NULL, "I", 0x1, 12, 13, 14, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithOrgSpongycastleCryptoBlockCipher:);
  methods[2].selector = @selector(getUnderlyingCipher);
  methods[3].selector = @selector(init__WithBoolean:withOrgSpongycastleCryptoCipherParameters:);
  methods[4].selector = @selector(getBlockSize);
  methods[5].selector = @selector(getUpdateOutputSizeWithInt:);
  methods[6].selector = @selector(getOutputSizeWithInt:);
  methods[7].selector = @selector(processByteWithByte:withByteArray:withInt:);
  methods[8].selector = @selector(processBytesWithByteArray:withInt:withInt:withByteArray:withInt:);
  methods[9].selector = @selector(doFinalWithByteArray:withInt:);
  methods[10].selector = @selector(reset);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "buf_PAdESDefaultBufferedBlockCipher_", "[B", .constantValue.asLong = 0, 0x4, 15, -1, -1, -1 },
    { "bufOff_PAdESDefaultBufferedBlockCipher_", "I", .constantValue.asLong = 0, 0x4, 16, -1, -1, -1 },
    { "forEncryption_PAdESDefaultBufferedBlockCipher_", "Z", .constantValue.asLong = 0, 0x4, 17, -1, -1, -1 },
    { "cipher_PAdESDefaultBufferedBlockCipher_", "LOrgSpongycastleCryptoBlockCipher;", .constantValue.asLong = 0, 0x4, 18, -1, -1, -1 },
    { "mbCipher_", "LComAowagieTextPdfBouncycastleMultiBlockCipher;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "partialBlockOkay_PAdESDefaultBufferedBlockCipher_", "Z", .constantValue.asLong = 0, 0x4, 19, -1, -1, -1 },
    { "pgpCFB_PAdESDefaultBufferedBlockCipher_", "Z", .constantValue.asLong = 0, 0x4, 20, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgSpongycastleCryptoBlockCipher;", "init", "ZLOrgSpongycastleCryptoCipherParameters;", "LJavaLangIllegalArgumentException;", "getUpdateOutputSize", "I", "getOutputSize", "processByte", "B[BI", "LOrgSpongycastleCryptoDataLengthException;LJavaLangIllegalStateException;", "processBytes", "[BII[BI", "doFinal", "[BI", "LOrgSpongycastleCryptoDataLengthException;LJavaLangIllegalStateException;LOrgSpongycastleCryptoInvalidCipherTextException;", "buf", "bufOff", "forEncryption", "cipher", "partialBlockOkay", "pgpCFB" };
  static const J2ObjcClassInfo _ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher = { "PAdESDefaultBufferedBlockCipher", "com.aowagie.text.pdf.bouncycastle", ptrTable, methods, fields, 7, 0x1, 11, 7, -1, -1, -1, -1, -1 };
  return &_ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher;
}

@end


#line 37
void ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_init(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *self) {
  OrgSpongycastleCryptoBufferedBlockCipher_init(self);
}


#line 37
ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *new_ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_init() {
  J2OBJC_NEW_IMPL(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher, init)
}


#line 37
ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *create_ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_init() {
  J2OBJC_CREATE_IMPL(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher, init)
}


#line 46
void ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *self, id<OrgSpongycastleCryptoBlockCipher> cipher) {
  OrgSpongycastleCryptoBufferedBlockCipher_init(self);
  
#line 49
  self->cipher_PAdESDefaultBufferedBlockCipher_ = cipher;
  
#line 51
  if ([ComAowagieTextPdfBouncycastleMultiBlockCipher_class_() isInstance:cipher]) {
    
#line 53
    self->mbCipher_ = (id<ComAowagieTextPdfBouncycastleMultiBlockCipher>) cast_check(cipher, ComAowagieTextPdfBouncycastleMultiBlockCipher_class_());
    self->buf_PAdESDefaultBufferedBlockCipher_ = [IOSByteArray newArrayWithLength:[((id<ComAowagieTextPdfBouncycastleMultiBlockCipher>) nil_chk(self->mbCipher_)) getMultiBlockSize]];
  }
  else {
    
#line 58
    self->mbCipher_ = nil;
    self->buf_PAdESDefaultBufferedBlockCipher_ = [IOSByteArray newArrayWithLength:[((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher)) getBlockSize]];
  }
  
#line 62
  self->bufOff_PAdESDefaultBufferedBlockCipher_ = 0;
  
#line 67
  NSString *name = [((id<OrgSpongycastleCryptoBlockCipher>) nil_chk(cipher)) getAlgorithmName];
  jint idx = [((NSString *) nil_chk(name)) java_indexOf:'/'] + 1;
  
#line 70
  self->pgpCFB_PAdESDefaultBufferedBlockCipher_ = (idx > 0 && [name java_hasPrefix:@"PGP" offset:idx]);
  
#line 72
  if (self->pgpCFB_PAdESDefaultBufferedBlockCipher_ || [OrgSpongycastleCryptoStreamCipher_class_() isInstance:cipher]) {
    
#line 74
    self->partialBlockOkay_PAdESDefaultBufferedBlockCipher_ = true;
  }
  else {
    
#line 78
    self->partialBlockOkay_PAdESDefaultBufferedBlockCipher_ = (idx > 0 && ([name java_hasPrefix:@"OpenPGP" offset:idx]));
  }
}


#line 46
ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *new_ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(id<OrgSpongycastleCryptoBlockCipher> cipher) {
  J2OBJC_NEW_IMPL(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher, initWithOrgSpongycastleCryptoBlockCipher_, cipher)
}


#line 46
ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher *create_ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher_initWithOrgSpongycastleCryptoBlockCipher_(id<OrgSpongycastleCryptoBlockCipher> cipher) {
  J2OBJC_CREATE_IMPL(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher, initWithOrgSpongycastleCryptoBlockCipher_, cipher)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAowagieTextPdfBouncycastlePAdESDefaultBufferedBlockCipher)
