//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesTrisigner.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/afirma/core/AOException.h"
#include "es/gob/afirma/core/signers/AOSignConstants.h"
#include "es/gob/afirma/ios/PadesTrisigner.h"
#include "es/gob/afirma/signers/pades/InvalidPdfException.h"
#include "es/gob/afirma/signers/pades/PAdESTriPhaseSigner.h"
#include "es/gob/afirma/signers/pades/PdfSignResult.h"
#include "es/gob/afirma/signers/pades/PdfUtil.h"
#include "es/gob/afirma/signers/pades/common/PdfExtraParams.h"
#include "java/lang/Boolean.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/security/NoSuchAlgorithmException.h"
#include "java/security/cert/Certificate.h"
#include "java/security/cert/X509Certificate.h"
#include "java/util/GregorianCalendar.h"
#include "java/util/Locale.h"
#include "java/util/Properties.h"
#include "java/util/logging/Logger.h"

#if !__has_feature(objc_arc)
#error "es/gob/afirma/ios/PadesTrisigner must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobAfirmaIosPadesTrisigner ()

+ (JavaUtilProperties *)getExtraParamsWithJavaUtilProperties:(JavaUtilProperties *)extraParams;

+ (void)checkParamsWithNSString:(NSString *)algorithm
         withJavaUtilProperties:(JavaUtilProperties *)extraParams;

@end

inline JavaUtilLoggingLogger *EsGobAfirmaIosPadesTrisigner_get_LOGGER(void);
static JavaUtilLoggingLogger *EsGobAfirmaIosPadesTrisigner_LOGGER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobAfirmaIosPadesTrisigner, LOGGER, JavaUtilLoggingLogger *)

__attribute__((unused)) static JavaUtilProperties *EsGobAfirmaIosPadesTrisigner_getExtraParamsWithJavaUtilProperties_(JavaUtilProperties *extraParams);

__attribute__((unused)) static void EsGobAfirmaIosPadesTrisigner_checkParamsWithNSString_withJavaUtilProperties_(NSString *algorithm, JavaUtilProperties *extraParams);

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesTrisigner.java"

J2OBJC_INITIALIZED_DEFN(EsGobAfirmaIosPadesTrisigner)


#line 19
@implementation EsGobAfirmaIosPadesTrisigner

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 19
- (instancetype)init {
  EsGobAfirmaIosPadesTrisigner_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 23
+ (EsGobAfirmaSignersPadesPdfSignResult *)presignWithByteArray:(IOSByteArray *)inPDF
                                                  withNSString:(NSString *)signAlgorithm
                          withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                                        withJavaUtilProperties:(JavaUtilProperties *)xParams {
  return EsGobAfirmaIosPadesTrisigner_presignWithByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(inPDF, signAlgorithm, certChain, xParams);
}


#line 61
+ (JavaUtilProperties *)getExtraParamsWithJavaUtilProperties:(JavaUtilProperties *)extraParams {
  return EsGobAfirmaIosPadesTrisigner_getExtraParamsWithJavaUtilProperties_(extraParams);
}


#line 68
+ (void)checkParamsWithNSString:(NSString *)algorithm
         withJavaUtilProperties:(JavaUtilProperties *)extraParams {
  EsGobAfirmaIosPadesTrisigner_checkParamsWithNSString_withJavaUtilProperties_(algorithm, extraParams);
}


#line 120
+ (IOSByteArray *)postsignWithByteArray:(IOSByteArray *)inPDF
withEsGobAfirmaSignersPadesPdfSignResult:(EsGobAfirmaSignersPadesPdfSignResult *)pre
                          withByteArray:(IOSByteArray *)interSign
                           withNSString:(NSString *)signAlgorithm
   withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                 withJavaUtilProperties:(JavaUtilProperties *)xParams {
  return EsGobAfirmaIosPadesTrisigner_postsignWithByteArray_withEsGobAfirmaSignersPadesPdfSignResult_withByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(inPDF, pre, interSign, signAlgorithm, certChain, xParams);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaSignersPadesPdfSignResult;", 0x8, 0, 1, 2, -1, -1, -1 },
    { NULL, "LJavaUtilProperties;", 0xa, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0xa, 5, 6, -1, -1, -1, -1 },
    { NULL, "[B", 0x8, 7, 8, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(presignWithByteArray:withNSString:withJavaSecurityCertCertificateArray:withJavaUtilProperties:);
  methods[2].selector = @selector(getExtraParamsWithJavaUtilProperties:);
  methods[3].selector = @selector(checkParamsWithNSString:withJavaUtilProperties:);
  methods[4].selector = @selector(postsignWithByteArray:withEsGobAfirmaSignersPadesPdfSignResult:withByteArray:withNSString:withJavaSecurityCertCertificateArray:withJavaUtilProperties:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOGGER", "LJavaUtilLoggingLogger;", .constantValue.asLong = 0, 0x1a, -1, 9, -1, -1 },
  };
  static const void *ptrTable[] = { "presign", "[BLNSString;[LJavaSecurityCertCertificate;LJavaUtilProperties;", "LEsGobAfirmaCoreAOException;LJavaIoIOException;", "getExtraParams", "LJavaUtilProperties;", "checkParams", "LNSString;LJavaUtilProperties;", "postsign", "[BLEsGobAfirmaSignersPadesPdfSignResult;[BLNSString;[LJavaSecurityCertCertificate;LJavaUtilProperties;", &EsGobAfirmaIosPadesTrisigner_LOGGER };
  static const J2ObjcClassInfo _EsGobAfirmaIosPadesTrisigner = { "PadesTrisigner", "es.gob.afirma.ios", ptrTable, methods, fields, 7, 0x1, 5, 1, -1, -1, -1, -1, -1 };
  return &_EsGobAfirmaIosPadesTrisigner;
}

+ (void)initialize {
  if (self == [EsGobAfirmaIosPadesTrisigner class]) {
    EsGobAfirmaIosPadesTrisigner_LOGGER = JavaUtilLoggingLogger_getLoggerWithNSString_(
#line 21
    @"es.gob.afirma");
    J2OBJC_SET_INITIALIZED(EsGobAfirmaIosPadesTrisigner)
  }
}

@end


#line 19
void EsGobAfirmaIosPadesTrisigner_init(EsGobAfirmaIosPadesTrisigner *self) {
  NSObject_init(self);
}


#line 19
EsGobAfirmaIosPadesTrisigner *new_EsGobAfirmaIosPadesTrisigner_init() {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPadesTrisigner, init)
}


#line 19
EsGobAfirmaIosPadesTrisigner *create_EsGobAfirmaIosPadesTrisigner_init() {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPadesTrisigner, init)
}

EsGobAfirmaSignersPadesPdfSignResult *EsGobAfirmaIosPadesTrisigner_presignWithByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(IOSByteArray *inPDF, NSString *signAlgorithm, IOSObjectArray *certChain, JavaUtilProperties *xParams) {
  EsGobAfirmaIosPadesTrisigner_initialize();
  
#line 29
  NSString *algorithm = signAlgorithm != nil ? signAlgorithm : EsGobAfirmaCoreSignersAOSignConstants_DEFAULT_SIGN_ALGO;
  JavaUtilProperties *extraParams = EsGobAfirmaIosPadesTrisigner_getExtraParamsWithJavaUtilProperties_(xParams);
  
#line 32
  EsGobAfirmaIosPadesTrisigner_checkParamsWithNSString_withJavaUtilProperties_(algorithm, extraParams);
  
#line 34
  IOSObjectArray *certificateChain = JavaLangBoolean_parseBooleanWithNSString_([((JavaUtilProperties *) nil_chk(extraParams)) getPropertyWithNSString:EsGobAfirmaSignersPadesCommonPdfExtraParams_INCLUDE_ONLY_SIGNNING_CERTIFICATE withNSString:[((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, FALSE))) description]]) ? [IOSObjectArray newArrayWithObjects:(id[]){
#line 35
    (JavaSecurityCertX509Certificate *) cast_chk(IOSObjectArray_Get(nil_chk(certChain), 0), [JavaSecurityCertX509Certificate class]) } count:1 type:JavaSecurityCertX509Certificate_class_()] :
#line 36
    certChain;
    
#line 38
    JavaUtilGregorianCalendar *signTime = EsGobAfirmaSignersPadesPdfUtil_getSignTimeWithNSString_([extraParams getPropertyWithNSString:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGN_TIME]);
    
#line 40
    IOSByteArray *data = inPDF;
    
#line 43
    EsGobAfirmaSignersPadesPdfSignResult *pre;
    @try {
      pre = EsGobAfirmaSignersPadesPAdESTriPhaseSigner_preSignWithNSString_withByteArray_withJavaSecurityCertCertificateArray_withJavaUtilGregorianCalendar_withJavaUtilProperties_withBoolean_(
#line 46
      algorithm,
#line 47
      data,
#line 48
      certificateChain,
#line 49
      signTime,
#line 50
      extraParams,
#line 51
      true);
    }
    @catch (
#line 54
    EsGobAfirmaSignersPadesInvalidPdfException *e) {
      @throw e;
    }
    
#line 58
    return pre;
  }


#line 61
JavaUtilProperties *EsGobAfirmaIosPadesTrisigner_getExtraParamsWithJavaUtilProperties_(JavaUtilProperties *extraParams) {
  EsGobAfirmaIosPadesTrisigner_initialize();
  
#line 62
  JavaUtilProperties *newExtraParams = extraParams != nil ?
#line 63
  (JavaUtilProperties *) cast_chk([extraParams java_clone], [JavaUtilProperties class]) : new_JavaUtilProperties_init();
  
#line 65
  return newExtraParams;
}


#line 68
void EsGobAfirmaIosPadesTrisigner_checkParamsWithNSString_withJavaUtilProperties_(NSString *algorithm, JavaUtilProperties *extraParams) {
  EsGobAfirmaIosPadesTrisigner_initialize();
  if ([((NSString *) nil_chk([((NSString *) nil_chk(algorithm)) java_uppercaseStringWithJRELocale:JreLoadStatic(JavaUtilLocale, US)])) java_hasPrefix:@"MD"]) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"PAdES no permite huellas digitales MD2 o MD5 (Decision 130/2011 CE)");
  }
  
#line 74
  NSString *profile = [((JavaUtilProperties *) nil_chk(extraParams)) getPropertyWithNSString:EsGobAfirmaSignersPadesCommonPdfExtraParams_PROFILE];
  
#line 77
  if ([((NSString *) nil_chk(EsGobAfirmaCoreSignersAOSignConstants_SIGN_PROFILE_BASELINE)) java_equalsIgnoreCase:profile]) {
    if (EsGobAfirmaCoreSignersAOSignConstants_isSHA1SignatureAlgorithmWithNSString_(algorithm)) {
      [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesTrisigner_LOGGER)) warningWithNSString:JreStrcat("$$$", @"El algoritmo '", algorithm, @"' no esta recomendado para su uso en las firmas baseline")];
    }
    
#line 82
    if ([extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGNATURE_SUBFILTER]) {
      [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesTrisigner_LOGGER)) warningWithNSString:JreStrcat("$$$$", @"Se ignorara el valor establecido en el parametro '",
#line 84
      EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGNATURE_SUBFILTER, @"' ya que en las firmas baseline el subfiltro siempre sera ",
#line 86
      EsGobAfirmaCoreSignersAOSignConstants_PADES_SUBFILTER_BES)];
      (void) [extraParams removeWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGNATURE_SUBFILTER];
    }
  }
  
#line 93
  if ([extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_COMMITMENT_TYPE_INDICATIONS] &&
#line 94
  ![EsGobAfirmaCoreSignersAOSignConstants_SIGN_PROFILE_BASELINE java_equalsIgnoreCase:profile] &&
#line 95
  ![extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_POLICY_IDENTIFIER]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesTrisigner_LOGGER)) warningWithNSString:@"Se ignoraran los commitment type indications establecidos por no estar permitidos en las firmas PAdES-EPES"];
    (void) [extraParams removeWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_COMMITMENT_TYPE_INDICATIONS];
  }
  
#line 102
  if ([extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGN_REASON] &&
#line 103
  [extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_POLICY_IDENTIFIER]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesTrisigner_LOGGER)) warningWithNSString:@"Se ignorara la razon de firma establecida por haberse indicado una politica de firma"];
    (void) [extraParams removeWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGN_REASON];
  }
  
#line 112
  if ([extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_SIGN_REASON] &&
#line 113
  [extraParams containsKeyWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_COMMITMENT_TYPE_INDICATIONS]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesTrisigner_LOGGER)) warningWithNSString:@"Se ignoraran los commitment type indications establecidos por haberse indicado una razon de firma"];
    (void) [extraParams removeWithId:EsGobAfirmaSignersPadesCommonPdfExtraParams_COMMITMENT_TYPE_INDICATIONS];
  }
}


#line 120
IOSByteArray *EsGobAfirmaIosPadesTrisigner_postsignWithByteArray_withEsGobAfirmaSignersPadesPdfSignResult_withByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(IOSByteArray *inPDF, EsGobAfirmaSignersPadesPdfSignResult *pre, IOSByteArray *interSign, NSString *signAlgorithm, IOSObjectArray *certChain, JavaUtilProperties *xParams) {
  EsGobAfirmaIosPadesTrisigner_initialize();
  
#line 127
  NSString *algorithm = signAlgorithm != nil ? signAlgorithm : EsGobAfirmaCoreSignersAOSignConstants_DEFAULT_SIGN_ALGO;
  JavaUtilProperties *extraParams = EsGobAfirmaIosPadesTrisigner_getExtraParamsWithJavaUtilProperties_(xParams);
  
#line 130
  EsGobAfirmaIosPadesTrisigner_checkParamsWithNSString_withJavaUtilProperties_(algorithm, extraParams);
  
#line 132
  IOSObjectArray *certificateChain = JavaLangBoolean_parseBooleanWithNSString_([((JavaUtilProperties *) nil_chk(extraParams)) getPropertyWithNSString:EsGobAfirmaSignersPadesCommonPdfExtraParams_INCLUDE_ONLY_SIGNNING_CERTIFICATE withNSString:[((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, FALSE))) description]]) ? [IOSObjectArray newArrayWithObjects:(id[]){
#line 133
    (JavaSecurityCertX509Certificate *) cast_chk(IOSObjectArray_Get(nil_chk(certChain), 0), [JavaSecurityCertX509Certificate class]) } count:1 type:JavaSecurityCertX509Certificate_class_()] :
#line 134
    certChain;
    
#line 136
    IOSByteArray *data = inPDF;
    
#line 138
    @try {
      return EsGobAfirmaSignersPadesPAdESTriPhaseSigner_postSignWithNSString_withByteArray_withJavaSecurityCertCertificateArray_withByteArray_withEsGobAfirmaSignersPadesPdfSignResult_withEsGobAfirmaCoreSignersSignEnhancer_withJavaUtilProperties_withBoolean_(
#line 140
      algorithm,
#line 141
      data,
#line 142
      certificateChain,
#line 143
      interSign,
#line 144
      pre,
#line 145
      nil,
#line 146
      nil,
#line 147
      true);
    }
    @catch (
#line 150
    JavaSecurityNoSuchAlgorithmException *e) {
      @throw new_EsGobAfirmaCoreAOException_initWithNSString_withJavaLangThrowable_(JreStrcat("$@", @"Error el en algoritmo de firma: ", e), e);
    }
  }

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobAfirmaIosPadesTrisigner)
