//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesSignerWrapper.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/afirma/core/AOCancelledOperationException.h"
#include "es/gob/afirma/core/AOException.h"
#include "es/gob/afirma/ios/PadesSignerWrapper.h"
#include "es/gob/afirma/ios/PadesTrisigner.h"
#include "es/gob/afirma/ios/PresignResult.h"
#include "es/gob/afirma/ios/SignatureError.h"
#include "es/gob/afirma/ios/SignatureResult.h"
#include "es/gob/afirma/ios/SupportRetry.h"
#include "es/gob/afirma/signers/pades/AOPDFSigner.h"
#include "es/gob/afirma/signers/pades/IncorrectPageException.h"
#include "es/gob/afirma/signers/pades/InvalidPdfException.h"
#include "es/gob/afirma/signers/pades/InvalidSignaturePositionException.h"
#include "es/gob/afirma/signers/pades/PdfSignResult.h"
#include "es/gob/afirma/signers/pades/common/BadPdfPasswordException.h"
#include "es/gob/afirma/signers/pades/common/PdfExtraParams.h"
#include "es/gob/afirma/signers/pades/common/PdfFormModifiedException.h"
#include "es/gob/afirma/signers/pades/common/PdfHasUnregisteredSignaturesException.h"
#include "es/gob/afirma/signers/pades/common/PdfIsCertifiedException.h"
#include "es/gob/afirma/signers/pades/common/PdfIsPasswordProtectedException.h"
#include "es/gob/afirma/signers/pades/common/SuspectedPSAException.h"
#include "java/io/IOException.h"
#include "java/lang/Boolean.h"
#include "java/lang/Throwable.h"
#include "java/security/PrivateKey.h"
#include "java/util/Properties.h"
#include "java/util/logging/Level.h"
#include "java/util/logging/Logger.h"

@class EsGobAfirmaIosPadesSignerWrapper_ErrorResult;

#if !__has_feature(objc_arc)
#error "es/gob/afirma/ios/PadesSignerWrapper must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobAfirmaIosPadesSignerWrapper () {
 @public
  EsGobAfirmaSignersPadesAOPDFSigner *signer_;
}

+ (EsGobAfirmaIosPadesSignerWrapper_ErrorResult *)identifyErrorWithJavaLangThrowable:(JavaLangThrowable *)e;

@end

J2OBJC_FIELD_SETTER(EsGobAfirmaIosPadesSignerWrapper, signer_, EsGobAfirmaSignersPadesAOPDFSigner *)

inline JavaUtilLoggingLogger *EsGobAfirmaIosPadesSignerWrapper_get_LOGGER(void);
static JavaUtilLoggingLogger *EsGobAfirmaIosPadesSignerWrapper_LOGGER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobAfirmaIosPadesSignerWrapper, LOGGER, JavaUtilLoggingLogger *)

__attribute__((unused)) static EsGobAfirmaIosPadesSignerWrapper_ErrorResult *EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(JavaLangThrowable *e);

/*!
 @brief Conjunto de codigo de error y mensaje asociado.
 */
@interface EsGobAfirmaIosPadesSignerWrapper_ErrorResult : NSObject {
 @public
  jint error_;
  NSString *message_;
  EsGobAfirmaIosSupportRetry *supportRetry_;
}

- (instancetype)initWithInt:(jint)error
               withNSString:(NSString *)message;

- (instancetype)initWithInt:(jint)error
               withNSString:(NSString *)message
withEsGobAfirmaIosSupportRetry:(EsGobAfirmaIosSupportRetry *)supportRetry;

- (jint)getError;

- (NSString *)getMessage;

- (EsGobAfirmaIosSupportRetry *)getSupportRetry;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaIosPadesSignerWrapper_ErrorResult)

J2OBJC_FIELD_SETTER(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, message_, NSString *)
J2OBJC_FIELD_SETTER(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, supportRetry_, EsGobAfirmaIosSupportRetry *)

__attribute__((unused)) static void EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosPadesSignerWrapper_ErrorResult *self, jint error, NSString *message);

__attribute__((unused)) static EsGobAfirmaIosPadesSignerWrapper_ErrorResult *new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(jint error, NSString *message) NS_RETURNS_RETAINED;

__attribute__((unused)) static EsGobAfirmaIosPadesSignerWrapper_ErrorResult *create_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(jint error, NSString *message);

__attribute__((unused)) static void EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosPadesSignerWrapper_ErrorResult *self, jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry);

__attribute__((unused)) static EsGobAfirmaIosPadesSignerWrapper_ErrorResult *new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry) NS_RETURNS_RETAINED;

__attribute__((unused)) static EsGobAfirmaIosPadesSignerWrapper_ErrorResult *create_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaIosPadesSignerWrapper_ErrorResult)

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesSignerWrapper.java"

J2OBJC_INITIALIZED_DEFN(EsGobAfirmaIosPadesSignerWrapper)


#line 24
@implementation EsGobAfirmaIosPadesSignerWrapper

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 30
- (instancetype)init {
  EsGobAfirmaIosPadesSignerWrapper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 43
- (EsGobAfirmaIosSignatureResult *)signWithByteArray:(IOSByteArray *)inPdf
                                        withNSString:(NSString *)signAlgorithm
                          withJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)key
                withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                              withJavaUtilProperties:(JavaUtilProperties *)xParams {
  
#line 49
  IOSByteArray *pdfSignature;
  @try {
    pdfSignature = [((EsGobAfirmaSignersPadesAOPDFSigner *) nil_chk(self->signer_)) signWithByteArray:inPdf withNSString:signAlgorithm withJavaSecurityPrivateKey:key withJavaSecurityCertCertificateArray:certChain withJavaUtilProperties:xParams];
  }
  @catch (
#line 52
  JavaLangThrowable *e) {
    EsGobAfirmaIosPadesSignerWrapper_ErrorResult *error = EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(e);
    return new_EsGobAfirmaIosSignatureResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_([((EsGobAfirmaIosPadesSignerWrapper_ErrorResult *) nil_chk(error)) getError], [error getMessage], [error getSupportRetry]);
  }
  return new_EsGobAfirmaIosSignatureResult_initWithByteArray_(pdfSignature);
}


#line 68
- (EsGobAfirmaIosPresignResult *)presignWithByteArray:(IOSByteArray *)inPdf
                                         withNSString:(NSString *)signAlgorithm
                 withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                               withJavaUtilProperties:(JavaUtilProperties *)xParams {
  
#line 74
  EsGobAfirmaIosPresignResult *preSignResult;
  
#line 76
  @try {
    EsGobAfirmaSignersPadesPdfSignResult *result = EsGobAfirmaIosPadesTrisigner_presignWithByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(inPdf, signAlgorithm, certChain, xParams);
    preSignResult = new_EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(result);
  }
  @catch (
#line 79
  JavaLangThrowable *e) {
    EsGobAfirmaIosPadesSignerWrapper_ErrorResult *error = EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(e);
    return new_EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_([((EsGobAfirmaIosPadesSignerWrapper_ErrorResult *) nil_chk(error)) getError], [error getMessage], [error getSupportRetry]);
  }
  
#line 84
  return preSignResult;
}


#line 96
- (EsGobAfirmaIosSignatureResult *)postsignWithByteArray:(IOSByteArray *)inPdf
                         withEsGobAfirmaIosPresignResult:(EsGobAfirmaIosPresignResult *)presignResult
                                           withByteArray:(IOSByteArray *)pkcs1
                                            withNSString:(NSString *)signAlgorithm
                    withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                                  withJavaUtilProperties:(JavaUtilProperties *)xParams {
  
#line 104
  IOSByteArray *result;
  @try {
    result = EsGobAfirmaIosPadesTrisigner_postsignWithByteArray_withEsGobAfirmaSignersPadesPdfSignResult_withByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(inPdf,
#line 107
    [((EsGobAfirmaIosPresignResult *) nil_chk(presignResult)) getPreSignature], pkcs1, signAlgorithm, certChain, xParams);
  }
  @catch (
#line 108
  JavaLangThrowable *e) {
    EsGobAfirmaIosPadesSignerWrapper_ErrorResult *error = EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(e);
    return new_EsGobAfirmaIosSignatureResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_([((EsGobAfirmaIosPadesSignerWrapper_ErrorResult *) nil_chk(error)) getError], [error getMessage], [error getSupportRetry]);
  }
  
#line 113
  return new_EsGobAfirmaIosSignatureResult_initWithByteArray_(result);
}


#line 116
+ (EsGobAfirmaIosPadesSignerWrapper_ErrorResult *)identifyErrorWithJavaLangThrowable:(JavaLangThrowable *)e {
  return EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(e);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosSignatureResult;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosPresignResult;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosSignatureResult;", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosPadesSignerWrapper_ErrorResult;", 0xa, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(signWithByteArray:withNSString:withJavaSecurityPrivateKey:withJavaSecurityCertCertificateArray:withJavaUtilProperties:);
  methods[2].selector = @selector(presignWithByteArray:withNSString:withJavaSecurityCertCertificateArray:withJavaUtilProperties:);
  methods[3].selector = @selector(postsignWithByteArray:withEsGobAfirmaIosPresignResult:withByteArray:withNSString:withJavaSecurityCertCertificateArray:withJavaUtilProperties:);
  methods[4].selector = @selector(identifyErrorWithJavaLangThrowable:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LOGGER", "LJavaUtilLoggingLogger;", .constantValue.asLong = 0, 0x1a, -1, 8, -1, -1 },
    { "signer_", "LEsGobAfirmaSignersPadesAOPDFSigner;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "sign", "[BLNSString;LJavaSecurityPrivateKey;[LJavaSecurityCertCertificate;LJavaUtilProperties;", "presign", "[BLNSString;[LJavaSecurityCertCertificate;LJavaUtilProperties;", "postsign", "[BLEsGobAfirmaIosPresignResult;[BLNSString;[LJavaSecurityCertCertificate;LJavaUtilProperties;", "identifyError", "LJavaLangThrowable;", &EsGobAfirmaIosPadesSignerWrapper_LOGGER, "LEsGobAfirmaIosPadesSignerWrapper_ErrorResult;" };
  static const J2ObjcClassInfo _EsGobAfirmaIosPadesSignerWrapper = { "PadesSignerWrapper", "es.gob.afirma.ios", ptrTable, methods, fields, 7, 0x1, 5, 2, -1, 9, -1, -1, -1 };
  return &_EsGobAfirmaIosPadesSignerWrapper;
}

+ (void)initialize {
  if (self == [EsGobAfirmaIosPadesSignerWrapper class]) {
    EsGobAfirmaIosPadesSignerWrapper_LOGGER = JavaUtilLoggingLogger_getLoggerWithNSString_(
#line 26
    @"es.gob.afirma");
    J2OBJC_SET_INITIALIZED(EsGobAfirmaIosPadesSignerWrapper)
  }
}

@end


#line 30
void EsGobAfirmaIosPadesSignerWrapper_init(EsGobAfirmaIosPadesSignerWrapper *self) {
  NSObject_init(self);
  
#line 31
  self->signer_ = new_EsGobAfirmaSignersPadesAOPDFSigner_init();
}


#line 30
EsGobAfirmaIosPadesSignerWrapper *new_EsGobAfirmaIosPadesSignerWrapper_init() {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPadesSignerWrapper, init)
}


#line 30
EsGobAfirmaIosPadesSignerWrapper *create_EsGobAfirmaIosPadesSignerWrapper_init() {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPadesSignerWrapper, init)
}


#line 116
EsGobAfirmaIosPadesSignerWrapper_ErrorResult *EsGobAfirmaIosPadesSignerWrapper_identifyErrorWithJavaLangThrowable_(JavaLangThrowable *e) {
  EsGobAfirmaIosPadesSignerWrapper_initialize();
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonPdfIsPasswordProtectedException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"El PDF esta protegido por contrasena" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_PASSWORD_PROTECTED, [((JavaLangThrowable *) nil_chk(e)) getMessage]);
  }
  else
#line 121
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonBadPdfPasswordException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"La contrasena del PDF no es correcta" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_BAD_PASSWORD, @"La contrasena del PDF no es correcta");
  }
  else
#line 124
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesInvalidPdfException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"El documento no es un PDF soportado" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_INVALID_PDF, @"El documento no es un PDF soportado");
  }
  else
#line 127
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesIncorrectPageException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"Se selecciono una pagina no valida para la rubrica del documento" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_INVALID_PAGE, @"Se selecciono una pagina no valida para la rubrica del documento");
  }
  else
#line 130
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesInvalidSignaturePositionException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"Se selecciono una posicion no valida para la rubrica del documento" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_INVALID_RUBRIC_POSITION, @"Se selecciono una posicion no valida para la rubrica del documento");
  }
  else
#line 133
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonPdfFormModifiedException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"Hay sospechas de que uno de los campos de formulario ha sido modificado despues de una firma anterior" withJavaLangThrowable:e];
    EsGobAfirmaIosSupportRetry *retry = new_EsGobAfirmaIosSupportRetry_initWithNSString_withNSString_(EsGobAfirmaSignersPadesCommonPdfExtraParams_ALLOW_SIGN_MODIFIED_FORM, [((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, TRUE))) description]);
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosSignatureError_FORM_MODIFIED, @"Hay sospechas de que uno de los campos de formulario ha sido modificado despues de una firma anterior", retry);
  }
  else
#line 137
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonSuspectedPSAException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"Hay sospechas de que el documento ha sido modificado despues de una firma anterior" withJavaLangThrowable:e];
    EsGobAfirmaIosSupportRetry *retry = new_EsGobAfirmaIosSupportRetry_initWithNSString_withNSString_(EsGobAfirmaSignersPadesCommonPdfExtraParams_ALLOW_SHADOW_ATTACK, [((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, TRUE))) description]);
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosSignatureError_SUSPECTED_PSA, @"Hay sospechas de que el documento ha sido modificado despues de una firma anterior", retry);
  }
  else
#line 141
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonPdfHasUnregisteredSignaturesException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"El documento tiene firmas anteriores sin registrar correctamente" withJavaLangThrowable:e];
    EsGobAfirmaIosSupportRetry *retry = new_EsGobAfirmaIosSupportRetry_initWithNSString_withNSString_(EsGobAfirmaSignersPadesCommonPdfExtraParams_ALLOW_COSIGNING_UNREGISTERED_SIGNATURES, [((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, TRUE))) description]);
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosSignatureError_UNREGISTER_SIGNATURES, @"El documento tiene firmas anteriores sin registrar correctamente", retry);
  }
  else
#line 145
  if ([e isKindOfClass:[EsGobAfirmaSignersPadesCommonPdfIsCertifiedException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"El documento esta certificado y una nueva firma puede invalidar las anteriores" withJavaLangThrowable:e];
    EsGobAfirmaIosSupportRetry *retry = new_EsGobAfirmaIosSupportRetry_initWithNSString_withNSString_(EsGobAfirmaSignersPadesCommonPdfExtraParams_ALLOW_COSIGNING_UNREGISTERED_SIGNATURES, [((JavaLangBoolean *) nil_chk(JreLoadStatic(JavaLangBoolean, TRUE))) description]);
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosSignatureError_CERTIFIED_DOCUMENT, @"El documento esta certificado y una nueva firma puede invalidar las anteriores", retry);
  }
  else
#line 149
  if ([e isKindOfClass:[EsGobAfirmaCoreAOCancelledOperationException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"Operacion cancelada por el usuario" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_CANCELLED, @"Operacion cancelada por el usuario");
  }
  else
#line 152
  if ([e isKindOfClass:[EsGobAfirmaCoreAOException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:JreStrcat("$$", @"Error desconocido durante la operacion: ", [((JavaLangThrowable *) nil_chk(e)) getMessage]) withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_UNKNOWN, [e getMessage]);
  }
  else
#line 155
  if ([e isKindOfClass:[JavaIoIOException class]]) {
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"Error en una operacion de lectura/escritura" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_INPUT_OUTPUT_ERROR, @"Error en una operacion de lectura/escritura");
  }
  else {
    
#line 159
    [((JavaUtilLoggingLogger *) nil_chk(EsGobAfirmaIosPadesSignerWrapper_LOGGER)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:@"Error desconocido grave" withJavaLangThrowable:e];
    return new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosSignatureError_UNKNOWN_SEVERE, @"Error desconocido grave");
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobAfirmaIosPadesSignerWrapper)

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesSignerWrapper.java"


#line 168
@implementation EsGobAfirmaIosPadesSignerWrapper_ErrorResult


#line 174
- (instancetype)initWithInt:(jint)error
               withNSString:(NSString *)message {
  EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(self, error, message);
  return self;
}

- (instancetype)initWithInt:(jint)error
               withNSString:(NSString *)message
withEsGobAfirmaIosSupportRetry:(EsGobAfirmaIosSupportRetry *)supportRetry {
  EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(self, error, message, supportRetry);
  return self;
}


#line 186
- (jint)getError {
  return self->error_;
}

- (NSString *)getMessage {
  return self->message_;
}

- (EsGobAfirmaIosSupportRetry *)getSupportRetry {
  return self->supportRetry_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosSupportRetry;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withNSString:);
  methods[1].selector = @selector(initWithInt:withNSString:withEsGobAfirmaIosSupportRetry:);
  methods[2].selector = @selector(getError);
  methods[3].selector = @selector(getMessage);
  methods[4].selector = @selector(getSupportRetry);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "error_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "message_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "supportRetry_", "LEsGobAfirmaIosSupportRetry;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "ILNSString;", "ILNSString;LEsGobAfirmaIosSupportRetry;", "LEsGobAfirmaIosPadesSignerWrapper;" };
  static const J2ObjcClassInfo _EsGobAfirmaIosPadesSignerWrapper_ErrorResult = { "ErrorResult", "es.gob.afirma.ios", ptrTable, methods, fields, 7, 0xa, 5, 3, 2, -1, -1, -1, -1 };
  return &_EsGobAfirmaIosPadesSignerWrapper_ErrorResult;
}

@end


#line 174
void EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(EsGobAfirmaIosPadesSignerWrapper_ErrorResult *self, jint error, NSString *message) {
  NSObject_init(self);
  
#line 175
  self->error_ = error;
  self->message_ = message;
  self->supportRetry_ = nil;
}


#line 174
EsGobAfirmaIosPadesSignerWrapper_ErrorResult *new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(jint error, NSString *message) {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, initWithInt_withNSString_, error, message)
}


#line 174
EsGobAfirmaIosPadesSignerWrapper_ErrorResult *create_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_(jint error, NSString *message) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, initWithInt_withNSString_, error, message)
}


#line 180
void EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosPadesSignerWrapper_ErrorResult *self, jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry) {
  NSObject_init(self);
  
#line 181
  self->error_ = error;
  self->message_ = message;
  self->supportRetry_ = supportRetry;
}


#line 180
EsGobAfirmaIosPadesSignerWrapper_ErrorResult *new_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry) {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_, error, message, supportRetry)
}


#line 180
EsGobAfirmaIosPadesSignerWrapper_ErrorResult *create_EsGobAfirmaIosPadesSignerWrapper_ErrorResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint error, NSString *message, EsGobAfirmaIosSupportRetry *supportRetry) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPadesSignerWrapper_ErrorResult, initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_, error, message, supportRetry)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobAfirmaIosPadesSignerWrapper_ErrorResult)
