//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesSignerWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobAfirmaIosPadesSignerWrapper")
#ifdef RESTRICT_EsGobAfirmaIosPadesSignerWrapper
#define INCLUDE_ALL_EsGobAfirmaIosPadesSignerWrapper 0
#else
#define INCLUDE_ALL_EsGobAfirmaIosPadesSignerWrapper 1
#endif
#undef RESTRICT_EsGobAfirmaIosPadesSignerWrapper

#if !defined (EsGobAfirmaIosPadesSignerWrapper_) && (INCLUDE_ALL_EsGobAfirmaIosPadesSignerWrapper || defined(INCLUDE_EsGobAfirmaIosPadesSignerWrapper))
#define EsGobAfirmaIosPadesSignerWrapper_

@class EsGobAfirmaIosPresignResult;
@class EsGobAfirmaIosSignatureResult;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaUtilProperties;
@protocol JavaSecurityPrivateKey;

@interface EsGobAfirmaIosPadesSignerWrapper : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Firma un PDF en formato PAdES y devuelve el resultado de la operaci&oacute;n.
 @param inPdf Documento PDF que se desea firmar.
 @param signAlgorithm Algoritmo de firma.
 @param key Clave privada de firma.
 @param certChain Cadena de certificaci &oacute; n del certificado de firma.
 @param xParams Propiedades de configuraci &oacute; n del formato.
 @return Resultado de la firma, que puede haber terminado bien o mal.
 */
- (EsGobAfirmaIosSignatureResult *)postsignWithByteArray:(IOSByteArray *)inPdf
                         withEsGobAfirmaIosPresignResult:(EsGobAfirmaIosPresignResult *)presignResult
                                           withByteArray:(IOSByteArray *)pkcs1
                                            withNSString:(NSString *)signAlgorithm
                    withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                                  withJavaUtilProperties:(JavaUtilProperties *)xParams;

/*!
 @brief Firma un PDF en formato PAdES y devuelve el resultado de la operaci&oacute;n.
 @param inPdf Documento PDF que se desea firmar.
 @param signAlgorithm Algoritmo de firma.
 @param key Clave privada de firma.
 @param certChain Cadena de certificaci &oacute; n del certificado de firma.
 @param xParams Propiedades de configuraci &oacute; n del formato.
 @return Resultado de la firma, que puede haber terminado bien o mal.
 */
- (EsGobAfirmaIosPresignResult *)presignWithByteArray:(IOSByteArray *)inPdf
                                         withNSString:(NSString *)signAlgorithm
                 withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                               withJavaUtilProperties:(JavaUtilProperties *)xParams;

/*!
 @brief Firma un PDF en formato PAdES y devuelve el resultado de la operaci&oacute;n.
 @param inPdf Documento PDF que se desea firmar.
 @param signAlgorithm Algoritmo de firma.
 @param key Clave privada de firma.
 @param certChain Cadena de certificaci &oacute; n del certificado de firma.
 @param xParams Propiedades de configuraci &oacute; n del formato.
 @return Resultado de la firma, que puede haber terminado bien o mal.
 */
- (EsGobAfirmaIosSignatureResult *)signWithByteArray:(IOSByteArray *)inPdf
                                        withNSString:(NSString *)signAlgorithm
                          withJavaSecurityPrivateKey:(id<JavaSecurityPrivateKey>)key
                withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                              withJavaUtilProperties:(JavaUtilProperties *)xParams;

@end

J2OBJC_STATIC_INIT(EsGobAfirmaIosPadesSignerWrapper)

FOUNDATION_EXPORT void EsGobAfirmaIosPadesSignerWrapper_init(EsGobAfirmaIosPadesSignerWrapper *self);

FOUNDATION_EXPORT EsGobAfirmaIosPadesSignerWrapper *new_EsGobAfirmaIosPadesSignerWrapper_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaIosPadesSignerWrapper *create_EsGobAfirmaIosPadesSignerWrapper_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaIosPadesSignerWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_EsGobAfirmaIosPadesSignerWrapper")
