//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PadesTrisigner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobAfirmaIosPadesTrisigner")
#ifdef RESTRICT_EsGobAfirmaIosPadesTrisigner
#define INCLUDE_ALL_EsGobAfirmaIosPadesTrisigner 0
#else
#define INCLUDE_ALL_EsGobAfirmaIosPadesTrisigner 1
#endif
#undef RESTRICT_EsGobAfirmaIosPadesTrisigner

#if !defined (EsGobAfirmaIosPadesTrisigner_) && (INCLUDE_ALL_EsGobAfirmaIosPadesTrisigner || defined(INCLUDE_EsGobAfirmaIosPadesTrisigner))
#define EsGobAfirmaIosPadesTrisigner_

@class EsGobAfirmaSignersPadesPdfSignResult;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaUtilProperties;

@interface EsGobAfirmaIosPadesTrisigner : NSObject

#pragma mark Public

- (instancetype)init;

#pragma mark Package-Private

+ (IOSByteArray *)postsignWithByteArray:(IOSByteArray *)inPDF
withEsGobAfirmaSignersPadesPdfSignResult:(EsGobAfirmaSignersPadesPdfSignResult *)pre
                          withByteArray:(IOSByteArray *)interSign
                           withNSString:(NSString *)signAlgorithm
   withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                 withJavaUtilProperties:(JavaUtilProperties *)xParams;

+ (EsGobAfirmaSignersPadesPdfSignResult *)presignWithByteArray:(IOSByteArray *)inPDF
                                                  withNSString:(NSString *)signAlgorithm
                          withJavaSecurityCertCertificateArray:(IOSObjectArray *)certChain
                                        withJavaUtilProperties:(JavaUtilProperties *)xParams;

@end

J2OBJC_STATIC_INIT(EsGobAfirmaIosPadesTrisigner)

FOUNDATION_EXPORT void EsGobAfirmaIosPadesTrisigner_init(EsGobAfirmaIosPadesTrisigner *self);

FOUNDATION_EXPORT EsGobAfirmaIosPadesTrisigner *new_EsGobAfirmaIosPadesTrisigner_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaIosPadesTrisigner *create_EsGobAfirmaIosPadesTrisigner_init(void);

FOUNDATION_EXPORT EsGobAfirmaSignersPadesPdfSignResult *EsGobAfirmaIosPadesTrisigner_presignWithByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(IOSByteArray *inPDF, NSString *signAlgorithm, IOSObjectArray *certChain, JavaUtilProperties *xParams);

FOUNDATION_EXPORT IOSByteArray *EsGobAfirmaIosPadesTrisigner_postsignWithByteArray_withEsGobAfirmaSignersPadesPdfSignResult_withByteArray_withNSString_withJavaSecurityCertCertificateArray_withJavaUtilProperties_(IOSByteArray *inPDF, EsGobAfirmaSignersPadesPdfSignResult *pre, IOSByteArray *interSign, NSString *signAlgorithm, IOSObjectArray *certChain, JavaUtilProperties *xParams);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaIosPadesTrisigner)

#endif

#pragma pop_macro("INCLUDE_ALL_EsGobAfirmaIosPadesTrisigner")
