//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PresignResult.java
//

#include "J2ObjC_source.h"
#include "es/gob/afirma/ios/PresignResult.h"
#include "es/gob/afirma/ios/SupportRetry.h"
#include "es/gob/afirma/signers/pades/PdfSignResult.h"

#if !__has_feature(objc_arc)
#error "es/gob/afirma/ios/PresignResult must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobAfirmaIosPresignResult () {
 @public
  EsGobAfirmaSignersPadesPdfSignResult *preSignature_;
  NSString *errorMessage_;
  jint errorCode_;
  EsGobAfirmaIosSupportRetry *retry_;
}

@end

J2OBJC_FIELD_SETTER(EsGobAfirmaIosPresignResult, preSignature_, EsGobAfirmaSignersPadesPdfSignResult *)
J2OBJC_FIELD_SETTER(EsGobAfirmaIosPresignResult, errorMessage_, NSString *)
J2OBJC_FIELD_SETTER(EsGobAfirmaIosPresignResult, retry_, EsGobAfirmaIosSupportRetry *)

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PresignResult.java"


#line 8
@implementation EsGobAfirmaIosPresignResult


#line 22
- (instancetype)initWithEsGobAfirmaSignersPadesPdfSignResult:(EsGobAfirmaSignersPadesPdfSignResult *)preSignature {
  EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(self, preSignature);
  return self;
}


#line 34
- (instancetype)initWithInt:(jint)errorCode
               withNSString:(NSString *)errorMessage {
  EsGobAfirmaIosPresignResult_initWithInt_withNSString_(self, errorCode, errorMessage);
  return self;
}


#line 43
- (instancetype)initWithInt:(jint)errorCode
               withNSString:(NSString *)errorMessage
withEsGobAfirmaIosSupportRetry:(EsGobAfirmaIosSupportRetry *)retry {
  EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(self, errorCode, errorMessage, retry);
  return self;
}


#line 54
- (EsGobAfirmaSignersPadesPdfSignResult *)getPreSignature {
  return self->preSignature_;
}


#line 62
- (jboolean)isError {
  return self->errorCode_ != -1;
}


#line 70
- (NSString *)getErrorMessage {
  return self->errorMessage_;
}


#line 78
- (jint)getErrorCode {
  return self->errorCode_;
}


#line 86
- (EsGobAfirmaIosSupportRetry *)getRetry {
  return self->retry_;
}


#line 94
- (jboolean)canRetry {
  return self->retry_ != nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaSignersPadesPdfSignResult;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEsGobAfirmaIosSupportRetry;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithEsGobAfirmaSignersPadesPdfSignResult:);
  methods[1].selector = @selector(initWithInt:withNSString:);
  methods[2].selector = @selector(initWithInt:withNSString:withEsGobAfirmaIosSupportRetry:);
  methods[3].selector = @selector(getPreSignature);
  methods[4].selector = @selector(isError);
  methods[5].selector = @selector(getErrorMessage);
  methods[6].selector = @selector(getErrorCode);
  methods[7].selector = @selector(getRetry);
  methods[8].selector = @selector(canRetry);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "preSignature_", "LEsGobAfirmaSignersPadesPdfSignResult;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "errorMessage_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "errorCode_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "retry_", "LEsGobAfirmaIosSupportRetry;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEsGobAfirmaSignersPadesPdfSignResult;", "ILNSString;", "ILNSString;LEsGobAfirmaIosSupportRetry;" };
  static const J2ObjcClassInfo _EsGobAfirmaIosPresignResult = { "PresignResult", "es.gob.afirma.ios", ptrTable, methods, fields, 7, 0x1, 9, 4, -1, -1, -1, -1, -1 };
  return &_EsGobAfirmaIosPresignResult;
}

@end


#line 22
void EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaIosPresignResult *self, EsGobAfirmaSignersPadesPdfSignResult *preSignature) {
  NSObject_init(self);
  
#line 23
  self->preSignature_ = preSignature;
  self->errorMessage_ = nil;
  self->errorCode_ = -1;
  self->retry_ = nil;
}


#line 22
EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaSignersPadesPdfSignResult *preSignature) {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPresignResult, initWithEsGobAfirmaSignersPadesPdfSignResult_, preSignature)
}


#line 22
EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaSignersPadesPdfSignResult *preSignature) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPresignResult, initWithEsGobAfirmaSignersPadesPdfSignResult_, preSignature)
}


#line 34
void EsGobAfirmaIosPresignResult_initWithInt_withNSString_(EsGobAfirmaIosPresignResult *self, jint errorCode, NSString *errorMessage) {
  EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(self, errorCode, errorMessage, nil);
}


#line 34
EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithInt_withNSString_(jint errorCode, NSString *errorMessage) {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPresignResult, initWithInt_withNSString_, errorCode, errorMessage)
}


#line 34
EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithInt_withNSString_(jint errorCode, NSString *errorMessage) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPresignResult, initWithInt_withNSString_, errorCode, errorMessage)
}


#line 43
void EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosPresignResult *self, jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry) {
  NSObject_init(self);
  
#line 44
  self->errorCode_ = errorCode;
  self->errorMessage_ = errorMessage;
  self->retry_ = retry;
  self->preSignature_ = nil;
}


#line 43
EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry) {
  J2OBJC_NEW_IMPL(EsGobAfirmaIosPresignResult, initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_, errorCode, errorMessage, retry)
}


#line 43
EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry) {
  J2OBJC_CREATE_IMPL(EsGobAfirmaIosPresignResult, initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_, errorCode, errorMessage, retry)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobAfirmaIosPresignResult)
