//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/es/gob/afirma/ios/PresignResult.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobAfirmaIosPresignResult")
#ifdef RESTRICT_EsGobAfirmaIosPresignResult
#define INCLUDE_ALL_EsGobAfirmaIosPresignResult 0
#else
#define INCLUDE_ALL_EsGobAfirmaIosPresignResult 1
#endif
#undef RESTRICT_EsGobAfirmaIosPresignResult

#if !defined (EsGobAfirmaIosPresignResult_) && (INCLUDE_ALL_EsGobAfirmaIosPresignResult || defined(INCLUDE_EsGobAfirmaIosPresignResult))
#define EsGobAfirmaIosPresignResult_

@class EsGobAfirmaIosSupportRetry;
@class EsGobAfirmaSignersPadesPdfSignResult;

/*!
 @brief Resultado de una operaci&oacute;n de firma PAdES.
 */
@interface EsGobAfirmaIosPresignResult : NSObject

#pragma mark Public

/*!
 @brief Resultado de error de una operaci&oacute;n de firma PAdES.
 @param errorCode C &oacute; digo de error.
 @param errorMessage Mensaje de error.
 */
- (instancetype)initWithInt:(jint)errorCode
               withNSString:(NSString *)errorMessage;

/*!
 @brief Resultado de error de una operaci&oacute;n de firma PAdES.
 @param errorCode C &oacute; digo de error.
 @param errorMessage Mensaje de error.
 */
- (instancetype)initWithInt:(jint)errorCode
               withNSString:(NSString *)errorMessage
withEsGobAfirmaIosSupportRetry:(EsGobAfirmaIosSupportRetry *)retry;

/*!
 @brief Resultado correcto de una operaci&oacute;n de firma PAdES.
 @param padesSignature
 */
- (instancetype)initWithEsGobAfirmaSignersPadesPdfSignResult:(EsGobAfirmaSignersPadesPdfSignResult *)preSignature;

/*!
 @brief Indica si se ha definido como reintentar la operaci&oacute;n para completarla correctamente.
 */
- (jboolean)canRetry;

/*!
 @brief Recupera el c&oacute;digo de error.
 @return C&oacute;digo de error o <code>-1</code> si no ocurri&oacute; ning&uacute;n error.
 */
- (jint)getErrorCode;

/*!
 @brief Recupera el mensaje de error.
 @return Mensaje de error o <code>null</code> si no ocurri&oacute; ning&uacute;n error.
 */
- (NSString *)getErrorMessage;

/*!
 @brief Recupera la firma PAdES generada.
 @return La firma o <code>null</code> si no finaliz&oacute; correctamente.
 */
- (EsGobAfirmaSignersPadesPdfSignResult *)getPreSignature;

/*!
 @brief Recupera la informaci&oacute;n para el reintento de la operaci&oacute;n.
 @return Informaci&oacute;n para el reintento de la operaci&oacute;n o <code>null</code> si no se defini&oacute;.
 */
- (EsGobAfirmaIosSupportRetry *)getRetry;

/*!
 @brief Identifica si la operaci&oacute;n fall&oacute;.
 @return <code>true</code> si el resultado es un error, <code>false</code> en caso contrario.
 */
- (jboolean)isError;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaIosPresignResult)

FOUNDATION_EXPORT void EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaIosPresignResult *self, EsGobAfirmaSignersPadesPdfSignResult *preSignature);

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaSignersPadesPdfSignResult *preSignature) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithEsGobAfirmaSignersPadesPdfSignResult_(EsGobAfirmaSignersPadesPdfSignResult *preSignature);

FOUNDATION_EXPORT void EsGobAfirmaIosPresignResult_initWithInt_withNSString_(EsGobAfirmaIosPresignResult *self, jint errorCode, NSString *errorMessage);

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithInt_withNSString_(jint errorCode, NSString *errorMessage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithInt_withNSString_(jint errorCode, NSString *errorMessage);

FOUNDATION_EXPORT void EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(EsGobAfirmaIosPresignResult *self, jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry);

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *new_EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaIosPresignResult *create_EsGobAfirmaIosPresignResult_initWithInt_withNSString_withEsGobAfirmaIosSupportRetry_(jint errorCode, NSString *errorMessage, EsGobAfirmaIosSupportRetry *retry);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaIosPresignResult)

#endif

#pragma pop_macro("INCLUDE_ALL_EsGobAfirmaIosPresignResult")
